import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8f7200",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#656357",
        "surface-dim": "#dadada",
        "on-secondary": "#ffffff",
        "secondary-container": "#e4dfd1",
        "on-secondary-fixed-variant": "#49473c",
        "on-primary-container": "#747676",
        "surface-tint": "#5d5f5f",
        "surface-container": "#eeeeee",
        "on-surface-variant": "#444748",
        "primary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#ffe088",
        "surface-bright": "#f9f9f9",
        "on-error-container": "#93000a",
        outline: "#747878",
        "surface-variant": "#e2e2e2",
        "outline-variant": "#c4c7c8",
        "on-background": "#1b1b1b",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#454747",
        "on-surface": "#1b1b1b",
        "inverse-primary": "#c6c6c7",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#241a00",
        primary: "#5d5f5f",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-container": "#ffffff",
        "on-secondary-fixed": "#1d1c13",
        tertiary: "#735c00",
        secondary: "#615e53",
        surface: "#f9f9f9",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#f3f3f3",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#cbc6b8",
        "primary-container": "#ffffff",
        "secondary-fixed": "#e7e2d4",
        "on-tertiary-fixed-variant": "#574500",
        "inverse-surface": "#303030",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
        "section-gap": "80px",
        "container-max": "1140px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "label-caps": ["var(--font-garamond)", "EB Garamond", "serif"],
        "display-lg-mobile": ["Myriad Pro", "Myriad", "sans-serif"],
        "headline-md": ["Myriad Pro", "Myriad", "sans-serif"],
        "body-md": ["var(--font-garamond)", "EB Garamond", "serif"],
        "body-lg": ["var(--font-garamond)", "EB Garamond", "serif"],
        "display-lg": ["Myriad Pro", "Myriad", "sans-serif"],
        "headline-sm": ["Myriad Pro", "Myriad", "sans-serif"],
        caslon: ["var(--font-caslon)", "Libre Caslon Text", "serif"],
      },
    },
  },
  plugins: [],
};

export default config;
